FROM node:18-alpine
WORKDIR /app
COPY . .
ENV DB_PASSWORD=hardcoded_db_pass_food_2024
ENV API_SECRET_KEY=api_secret_food_HARDCODED_XYZ123
ENV JWT_SECRET=jwt_hardcoded_food_ABCDEF0987654321
ENV AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
ENV AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
ENV STRIPE_SECRET_KEY=sk_live_hardcoded_food_1234567890abcdef
RUN npm install --production
EXPOSE 3000
CMD ["node", "index.js"]
